conda activate /home/ubuntu/StyleDiffusion/.conda
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 0.1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 5 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 10 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 0.1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 5 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 10 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 0.1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 5 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 10 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 0.1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 1 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 5 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 10 --style_loss_w 0.1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 0.1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 5 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 10 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 0.1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 5 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 10 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 0.1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 5 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 10 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 0.1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 1 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 5 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 10 --style_loss_w 1
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 0.1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 5 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 10 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 0.1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 5 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 10 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 0.1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 5 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 10 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 0.1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 1 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 5 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 10 --style_loss_w 5
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 0.1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 5 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 0.1 --l1_loss_w 10 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 0.1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 5 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 1 --l1_loss_w 10 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 0.1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 5 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 5 --l1_loss_w 10 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 0.1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 1 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 5 --style_loss_w 10
python main.py --style_image gogh.jpg --dir_loss 10 --l1_loss_w 10 --style_loss_w 10
